[phases.setup]
nixPkgs = ["python311", "zlib", "libjpeg", "libpng", "freetype", "lcms2", "libwebp", "openjpeg", "libtiff"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
